/Users/izerkoen/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Serving Flask app 'app_v2'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://10.173.10.246:5001
[33mPress CTRL+C to quit[0m
 * Restarting with stat
/Users/izerkoen/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 934-894-353
127.0.0.1 - - [07/Aug/2025 12:19:08] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2025 12:19:36] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2025 12:20:02] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2025 12:23:20] "POST /search_sku HTTP/1.1" 200 -
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
